name: classroom_live_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.1.7
  json_serializable: ^6.9.5
  json5_model:
    git:
      url: https://github.com/wilinz/json5_model.git

index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  libraries:
    - directory_path: lib
